// DAO Operations
export const CREATE_PROPOSAL = "CREATE_PROPOSAL";
export const CREATE_PROPOSAL_LOADING = "CREATE_PROPOSAL_LOADING";
export const CREATE_PROPOSAL_SUCCESS = "CREATE_PROPOSAL_SUCCESS";
export const CREATE_PROPOSAL_FAILED = "CREATE_PROPOSAL_FAILED";

export const VOTE_ON_PROPOSAL = "VOTE_ON_PROPOSAL";
export const VOTE_ON_PROPOSAL_LOADING = "VOTE_ON_PROPOSAL_LOADING";
export const VOTE_ON_PROPOSAL_SUCCESS = "VOTE_ON_PROPOSAL_SUCCESS";
export const VOTE_ON_PROPOSAL_FAILED = "VOTE_ON_PROPOSAL_FAILED";

export const EXECUTE_PROPOSAL = "EXECUTE_PROPOSAL";
export const EXECUTE_PROPOSAL_LOADING = "EXECUTE_PROPOSAL_LOADING";
export const EXECUTE_PROPOSAL_SUCCESS = "EXECUTE_PROPOSAL_SUCCESS";
export const EXECUTE_PROPOSAL_FAILED = "EXECUTE_PROPOSAL_FAILED";

export const WITHDRAW_FUNDS = "WITHDRAW_FUNDS";
export const WITHDRAW_FUNDS_LOADING = "WITHDRAW_FUNDS_LOADING";
export const WITHDRAW_FUNDS_SUCCESS = "WITHDRAW_FUNDS_SUCCESS";
export const WITHDRAW_FUNDS_FAILED = "WITHDRAW_FUNDS_FAILED";
