export const ADD_MEMBER = "ADD_MEMBER";
export const ADD_MEMBER_LOADING = "ADD_MEMBER_LOADING";
export const ADD_MEMBER_SUCCESS = "ADD_MEMBER_SUCCESS";
export const ADD_MEMBER_FAILED = "ADD_MEMBER_FAILED";

export const LOAD_MEMBER = "LOAD_MEMBER";
export const LOAD_MEMBER_LOADING = "LOAD_MEMBER_LOADING";
export const LOAD_MEMBER_SUCCESS = "LOAD_MEMBER_SUCCESS";
export const LOAD_MEMBER_FAILED = "LOAD_MEMBER_FAILED";

export const UPDATE_MEMBER = "UPDATE_MEMBER";
export const UPDATE_MEMBER_LOADING = "UPDATE_MEMBER_LOADING";
export const UPDATE_MEMBER_SUCCESS = "UPDATE_MEMBER_SUCCESS";
export const UPDATE_MEMBER_FAILED = "UPDATE_MEMBER_FAILED";

export const DELETE_MEMBER = "DELETE_MEMBER";
export const DELETE_MEMBER_LOADING = "DELETE_MEMBER_LOADING";
export const DELETE_MEMBER_FAILED = "DELETE_MEMBER_FAILED";

export const VALIDATE_MEMBER_CACHE = "VALIDATE_MEMBER_CACHE";
export const INVALIDATE_MEMBER_CACHE = "INVALIDATE_MEMBER_CACHE";
