export const UPLOAD_DOCUMENT_IPFS = "UPLOAD_DOCUMENT_IPFS";
export const UPLOAD_DOCUMENT_IPFS_UPLOADING = "UPLOAD_DOCUMENT_IPFS_UPLOADING";
export const UPLOAD_DOCUMENT_IPFS_SUCCESS = "UPLOAD_DOCUMENT_IPFS_SUCCESS";
export const UPLOAD_DOCUMENT_IPFS_FAILED = "UPLOAD_DOCUMENT_IPFS_FAILED";

export const DOWNLOAD_DOCUMENT_IPFS = "DOWNLOAD_DOCUMENT_IPFS";
export const DOWNLOAD_DOCUMENT_IPFS_DOWNLOADING = "DOWNLOAD_DOCUMENT_IPFS_DOWNLOADING";
export const DOWNLOAD_DOCUMENT_IPFS_SUCCESS = "DOWNLOAD_DOCUMENT_IPFS_SUCCESS";
export const DOWNLOAD_DOCUMENT_IPFS_FAILED = "DOWNLOAD_DOCUMENT_IPFS_FAILED";

export const EDIT_DOCUMENT_IPFS = "EDIT_DOCUMENT_IPFS";
export const EDIT_DOCUMENT_IPFS_EDITING = "EDIT_DOCUMENT_IPFS_EDITING";
export const EDIT_DOCUMENT_IPFS_SUCCESS = "EDIT_DOCUMENT_IPFS_SUCCESS";
export const EDIT_DOCUMENT_IPFS_FAILED = "EDIT_DOCUMENT_IPFS_FAILED";

export const DELETE_DOCUMENT_IPFS = "DELETE_DOCUMENT_IPFS";
export const DELETE_DOCUMENT_IPFS_LOADING = "DELETE_DOCUMENT_IPFS_LOADING";
export const DELETE_DOCUMENT_IPFS_SUCCESS = "DELETE_DOCUMENT_IPFS_SUCCESS";
export const DELETE_DOCUMENT_IPFS_FAILED = "DELETE_DOCUMENT_IPFS_FAILED";